name: Deploy to Production

on:
  push:
    branches:
      - create-githubactions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Production via SSH
        env:
          SSH_HOST: ${{ secrets.PROD_URL_SERVER }}
          SSH_USER: ${{ secrets.PROD_USER_SERVER }}
          SSH_PASSWORD: ${{ secrets.PROD_PASSWORD_SERVER }}
        run: |
            set -x
            sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} << 'EOF'
            set -x
            echo "Connected to server"
            echo "Pulling latest changes from GitHub"
            cd /root/PROD/prj-final-front-back-tr-final-g6
            git switch create-githubactions
            git pull
            echo "Git pull completed"
            echo "Start DOCKER"
            docker compose -f docker-compose.prod.yml up -d --build
            echo "Docker compose up completed"
            echo "List of running containers"
            docker ps -a
            EOF