name: Deploy to Production

on:
  push:
    branches:
      - create-githubactions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Production via SSH
        env:
          SSH_HOST: ${{ secrets.PROD_URL_SERVER }}
          SSH_USER: ${{ secrets.PROD_USER_SERVER }}
          SSH_PASSWORD: ${{ secrets.PROD_PASSWORD_SERVER }}
        run: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} << 'EOF'
            echo "Connected to server"
            EOF
      - name: Update git
        run: |
            cd /root/PROD/prj-final-front-back-tr-final-g6
            git switch create-githubactions
            git pull